# Generated by Django 3.0.6 on 2020-06-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
